services:
  db:
    image: postgres:16.1
    command: postgres -c wal_level=logical -c max_wal_senders=1 -c max_replication_slots=1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: 
      context: .
      dockerfile: ./Dockerfiles/web/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8007:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
  
  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
